# File: .readthedocs.yaml (see #8731)
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#using-a-configuration-file
# #10318 : update to version 2 (i.e. use build directive) and use python 11.

version: 2

sphinx:
  configuration: docs/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"

python:
  install:
    - requirements: docs/requirements.txt
