# File: .readthedocs.yaml
# See https://docs.readthedocs.io/en/stable/guides/reproducible-builds.html#using-a-configuration-file

version: 2

sphinx:
  configuration: docs/conf.py

python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
